# Generated by Django 3.0.3 on 2020-09-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='detail',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
